name: Integration test

on: [push]

env:
  TORCH_DEVICE: "cpu"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install apt dependencies
        run: |
          sudo apt-get update
      - name: Install python dependencies
        run: |
          pip install poetry
          poetry install
          poetry run pip uninstall torch -y
          poetry run pip install torch --index-url https://download.pytorch.org/whl/cpu
      - name: Run benchmark test
        run: |
          poetry run python benchmarks/benchmark.py --max 5 temp.json
          poetry run python scripts/verify_benchmark_scores.py temp.json